/*
  This file will be overwritten by wxDev-C++ at every compile.
  Do not edit this file as your changes will be lost.
  You can, however, include this file and use the defines.
*/
#ifndef WMB_ASM_PRIVATE_H
#define WMB_ASM_PRIVATE_H

/* VERSION DEFINITIONS */
#define VER_STRING	"1.5.1.471"
#define VER_MAJOR	1
#define VER_MINOR	5
#define VER_RELEASE	1
#define VER_BUILD	471
#define COMPANY_NAME	"yellowstar"
#define FILE_VERSION	"1.5"
#define FILE_DESCRIPTION	"Assemble WMB captures into binaries to be played on an DS"
#define INTERNAL_NAME	"Wmb Asm"
#define LEGAL_COPYRIGHT	""
#define LEGAL_TRADEMARKS	""
#define ORIGINAL_FILENAME	"Wmb Asm"
#define PRODUCT_NAME	"Wmb Asm"
#define PRODUCT_VERSION	"1.5"

#endif /*WMB_ASM_PRIVATE_H*/
