/*
  This file will be overwritten by wxDev-C++ at every compile.
  Do not edit this file as your changes will be lost.
  You can, however, include this file and use the defines.
*/
#ifndef WMB_ASM_MODULE_PRIVATE_H
#define WMB_ASM_MODULE_PRIVATE_H

/* VERSION DEFINITIONS */
#define VER_STRING	"2.0.1.902"
#define VER_MAJOR	2
#define VER_MINOR	0
#define VER_RELEASE	1
#define VER_BUILD	902
#define COMPANY_NAME	"yellowstar"
#define FILE_VERSION	"2.0b r2"
#define FILE_DESCRIPTION	"Module for assembling WMB captures"
#define INTERNAL_NAME	"wmb_asm.dll"
#define LEGAL_COPYRIGHT	""
#define LEGAL_TRADEMARKS	""
#define ORIGINAL_FILENAME	"wmb_asm.dll"
#define PRODUCT_NAME	"wmb_asm.dll"
#define PRODUCT_VERSION	"2.0b r2"

#endif /*WMB_ASM_MODULE_PRIVATE_H*/
