/*
  This file will be overwritten by wxDev-C++ at every compile.
  Do not edit this file as your changes will be lost.
  You can, however, include this file and use the defines.
*/
#ifndef WMB_ASM_CMD_PRIVATE_H
#define WMB_ASM_CMD_PRIVATE_H

/* VERSION DEFINITIONS */
#define VER_STRING	"2.0.1.748"
#define VER_MAJOR	2
#define VER_MINOR	0
#define VER_RELEASE	1
#define VER_BUILD	748
#define COMPANY_NAME	"yellowstar"
#define FILE_VERSION	"2.0b r2"
#define FILE_DESCRIPTION	"Assemble WMB captures into an .nds to be played on an DS"
#define INTERNAL_NAME	"Wmb Asm"
#define LEGAL_COPYRIGHT	""
#define LEGAL_TRADEMARKS	""
#define ORIGINAL_FILENAME	"Wmb Asm"
#define PRODUCT_NAME	"Wmb Asm"
#define PRODUCT_VERSION	"2.0b r2"

#endif /*WMB_ASM_CMD_PRIVATE_H*/
