/*
  This file will be overwritten by wxDev-C++ at every compile.
  Do not edit this file as your changes will be lost.
  You can, however, include this file and use the defines.
*/
#ifndef WMB_ASM_FRONTEND_PRIVATE_H
#define WMB_ASM_FRONTEND_PRIVATE_H

/* VERSION DEFINITIONS */
#define VER_STRING	"1.0.1.90"
#define VER_MAJOR	1
#define VER_MINOR	0
#define VER_RELEASE	1
#define VER_BUILD	90
#define COMPANY_NAME	"yellowstar"
#define FILE_VERSION	"1.0"
#define FILE_DESCRIPTION	"Assemble WMB captures with a GUI"
#define INTERNAL_NAME	"wmb_asm_frontend"
#define LEGAL_COPYRIGHT	""
#define LEGAL_TRADEMARKS	""
#define ORIGINAL_FILENAME	"wmb_asm_frontend"
#define PRODUCT_NAME	"wmb_asm_frontend"
#define PRODUCT_VERSION	"1.0"

#endif /*WMB_ASM_FRONTEND_PRIVATE_H*/
